<?php

$this->headLink()
    ->prependStylesheet('/zf-api-first-admin/css/bootstrap-glyphicons.css')
    ->prependStylesheet('/zf-api-first-admin/css/wizard.css')
    ->prependStylesheet('/zf-api-first-admin/css/angular.treeview.css');
    

$this->headScript()->appendFile('/zf-api-first-admin/js/angular.js');
	
$this->inlineScript()
	 ->appendFile('/zf-api-first-admin/js/angular.treeview.js', 'text/javascript')
    ->appendFile('/zf-api-first-admin/js/app.js');

?>
<div id="main">
    <div id="content">
        <div class="container" ng-view>
        </div>
    </div>
</div>
