<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="/zf-api-first/js/jquery.min.js"></script>
    <script type="text/javascript" src="/zf-api-first/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/lodash.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/q.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/URI.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/URITemplate.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/hyperagent.js"></script>
    <script type="text/javascript" src="/zf-api-first-admin/js/angular.js"></script>
<!--    <script type="text/javascript" src="/zf-api-first-admin/js/angular.halparser.js"></script>-->
<!--    <script type="text/javascript" src="/zf-api-first-admin/js/angular.hal.js"></script>-->
    <link rel="stylesheet" type="text/css" href="/zf-api-first/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/zf-api-first/css/main.css" />
</head>
<body id="ng-app" ng-app="zfa1-admin">
    <a class="sr-only" href="#content"> … </a>
    <header class="navbar navbar-inverse navbar-fixed-top zfa1-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
                <a href="/admin" class="navbar-brand">
                    <img src="/zf-api-first/img/zfa1-logo.png">
                </a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".zfa1-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <nav class="collapse navbar-collapse zfa1-navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    <li class="zfa1-nav-dashboard active">
                        <a href="#">Dashboard</a>
                    </li>
                    <li>
                        <a href="/apidoc">API Doc</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="zf1a-module-navigation" ng-controller="ModuleListController">
        <div class="container">
            <span class="pull-left">Modules: </span>
            <button ng-hide="addModule" ng-click="addModule = true" id="create-module-button" class="btn btn-sm btn-primary pull-right" title="Create New API First Module" position="bottom" content="#create-module-form">
                Create New API 1st Module
            </button>
            <ul class="nav nav-pills zfa1-nav-pills">
                <li ng-repeat="module in modules">
                    <a href="#/module/{{ module.props.name }}/info">{{ module.props.namespace }}</a>
                </li>
            </ul>
        </div>
        <div ng-show="addModule" id="create-module-form" class="panel panel-default pull-right">
            <div class="panel-heading">Create A New API 1st Module</div>
            <div class="panel-body">
                <form ng-submit="createNewModule()">
                    <input type="text" ng-model="moduleName" placeholder="Module Name ...">
                    <button ng-click="addModule = false" type="button" class="btn btn-sm btn-default">Cancel</button>
                    <button type="submit" class="btn btn-sm btn-success">Create Module</button>
                </form>
            </div>
        </div>
    </div>

    <div class="zfa1-header" id="content">
        <div class="container">
            <h1>{{ pageTitle }}</h1>
            <p>{{ pageDescription }}</p>
        </div>
    </div>

    <div class="container bs-docs-container">
        <div class="row">
            <div class="col-md-3">
                <aside class="zfa1-sidebar" role="complementary">
                    <ul class="nav zfa1-sidenav" ng-controller="ViewNavigationController">
                        <li ng-repeat="item in items" ng-class="{active: section == item.id}">
                            <a ng-href="#{{ item.link }}">{{ item.name }}</a>
                        </li>
                    </ul>
                </aside>
            </div>
            <main class="col-md-9" role="main">
                <h1>{{ view.title }}</h1>
                <div id="content" ng-view></div>
            </main>
        </div>
    </div>

    <script type="text/javascript" src="/zf-api-first-admin/js/app.js"></script>
    </body>
</html>
