<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility/js/jquery.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility/js/bootstrap.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/lodash.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/q.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/URI.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/URITemplate.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/hyperagent.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/typeahead.min.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/angular.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/vendor/ng-tags-input.min.js') ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility/css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility/css/main.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility-admin/css/main.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility-admin/css/ng-tags-input.min.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility-admin/css/bootstrap-glyphicons.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->basePath('/zf-apigility-admin/css/typeahead.css') ?>" />
</head>
<body id="ng-app" ng-app="ag-admin">
    <a class="sr-only" href="#content"> … </a>
    <header class="navbar navbar-inverse navbar-fixed-top ag-admin-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
                <a href="<?= $this->url('zf-apigility-admin') ?>" class="navbar-brand">
                    <img src="<?= $this->basePath('/zf-apigility/img/ag-logo.png') ?>">
                </a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".ag-admin-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </header>

    <div class="ag-admin-module-navigation" ng-controller="ApiListController">
        <div class="container">
            <button ng-hide="showNewApiForm" ng-click="showNewApiForm = true" id="create-module-button" class="btn btn-sm btn-primary pull-right" title="Create New API" position="bottom" content="#create-api-form">
                Create New API
            </button>
            <span class="pull-left">APIs: </span>
            <ul class="nav nav-pills ag-admin-nav-pills">
                <li ng-repeat="api in apis" ng-class="{active: ($root.routeParams.apiName == api.name)}">
                    <a href="<?= $this->basePath('#/api/{{ api.name }}/info') ?>" ng-bind="api.namespace"></a>
                </li>
            </ul>
        </div>
        <div ng-show="showNewApiForm" id="create-api-form" class="panel panel-default pull-right">
            <div class="panel-heading">Create New API</div>
            <div class="panel-body">
                <form ng-submit="createNewApi()">
                    <input type="text" ng-model="apiName" placeholder="API Name ..." required="">
                    <button type="submit" class="btn btn-sm btn-success">Create API</button>
                    <button ng-click="resetForm()" type="button" class="btn btn-sm btn-warning">Cancel</button>
                </form>
            </div>
        </div>
    </div>

    <div class="ag-admin-header" id="content">
        <div class="container">
            <h1 ng-bind="pageTitle"></h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <view-navigation></view-navigation>
            </div>
            <main class="col-md-9" role="main">
                <h1 ng-bind="view.title"></h1>
                <div id="content" ng-view></div>
            </main>
        </div>
    </div>

    <script type="text/javascript" src="<?= $this->basePath('/zf-apigility-admin/js/app.js') ?>"></script>
    </body>
</html>
